/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZkSyncDidRegistryAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDelegate"
      | "attributes"
      | "changeOwner"
      | "changed"
      | "credentialDefinitions"
      | "delegates"
      | "identityOwner"
      | "owners"
      | "registerCredentialDefinition"
      | "registerRevocationRegistryDefinition"
      | "registerRevocationStatusList"
      | "registerSchema"
      | "revocationRegistryDefinitions"
      | "revocationStatusLists"
      | "revokeAttribute"
      | "revokeDelegate"
      | "schemas"
      | "setAttribute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialDefinitionRegistered"
      | "DIDAttributeChanged"
      | "DIDDelegateChanged"
      | "DIDOwnerChanged"
      | "RevocationRegistryDefinitionRegistered"
      | "RevocationStatusListRegistered"
      | "SchemaRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDelegate",
    values: [AddressLike, BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attributes",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwner",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialDefinitions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegates",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owners", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "registerCredentialDefinition",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRevocationRegistryDefinition",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRevocationStatusList",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSchema",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revocationRegistryDefinitions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revocationStatusLists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttribute",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegate",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "schemas", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setAttribute",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attributes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "credentialDefinitions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCredentialDefinition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRevocationRegistryDefinition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRevocationStatusList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revocationRegistryDefinitions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revocationStatusLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schemas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttribute",
    data: BytesLike
  ): Result;
}

export namespace CredentialDefinitionRegisteredEvent {
  export type InputTuple = [
    credentialDefinitionId: BytesLike,
    credentialDefinition: string
  ];
  export type OutputTuple = [
    credentialDefinitionId: string,
    credentialDefinition: string
  ];
  export interface OutputObject {
    credentialDefinitionId: string;
    credentialDefinition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDAttributeChangedEvent {
  export type InputTuple = [
    identity: AddressLike,
    name: BytesLike,
    value: BytesLike,
    validTo: BigNumberish,
    previousChange: BigNumberish
  ];
  export type OutputTuple = [
    identity: string,
    name: string,
    value: string,
    validTo: bigint,
    previousChange: bigint
  ];
  export interface OutputObject {
    identity: string;
    name: string;
    value: string;
    validTo: bigint;
    previousChange: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDDelegateChangedEvent {
  export type InputTuple = [
    identity: AddressLike,
    delegateType: BytesLike,
    delegate: AddressLike,
    validTo: BigNumberish,
    previousChange: BigNumberish
  ];
  export type OutputTuple = [
    identity: string,
    delegateType: string,
    delegate: string,
    validTo: bigint,
    previousChange: bigint
  ];
  export interface OutputObject {
    identity: string;
    delegateType: string;
    delegate: string;
    validTo: bigint;
    previousChange: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDOwnerChangedEvent {
  export type InputTuple = [
    identity: AddressLike,
    owner: AddressLike,
    previousChange: BigNumberish
  ];
  export type OutputTuple = [
    identity: string,
    owner: string,
    previousChange: bigint
  ];
  export interface OutputObject {
    identity: string;
    owner: string;
    previousChange: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevocationRegistryDefinitionRegisteredEvent {
  export type InputTuple = [
    revocationRegistryDefinitionId: BytesLike,
    revocationRegistryDefinition: string
  ];
  export type OutputTuple = [
    revocationRegistryDefinitionId: string,
    revocationRegistryDefinition: string
  ];
  export interface OutputObject {
    revocationRegistryDefinitionId: string;
    revocationRegistryDefinition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevocationStatusListRegisteredEvent {
  export type InputTuple = [
    revocationRegistryDefinitionId: BytesLike,
    timestamp: BigNumberish,
    revocationStatusList: string
  ];
  export type OutputTuple = [
    revocationRegistryDefinitionId: string,
    timestamp: bigint,
    revocationStatusList: string
  ];
  export interface OutputObject {
    revocationRegistryDefinitionId: string;
    timestamp: bigint;
    revocationStatusList: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SchemaRegisteredEvent {
  export type InputTuple = [schemaId: BytesLike, schema: string];
  export type OutputTuple = [schemaId: string, schema: string];
  export interface OutputObject {
    schemaId: string;
    schema: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZkSyncDidRegistryAbi extends BaseContract {
  connect(runner?: ContractRunner | null): ZkSyncDidRegistryAbi;
  waitForDeployment(): Promise<this>;

  interface: ZkSyncDidRegistryAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDelegate: TypedContractMethod<
    [
      identity: AddressLike,
      delegateType: BytesLike,
      delegate: AddressLike,
      validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  attributes: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  changeOwner: TypedContractMethod<
    [identity: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  changed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  credentialDefinitions: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  delegates: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  identityOwner: TypedContractMethod<[identity: AddressLike], [string], "view">;

  owners: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerCredentialDefinition: TypedContractMethod<
    [credentialDefinitionId: BytesLike, credentialDefinition: string],
    [void],
    "nonpayable"
  >;

  registerRevocationRegistryDefinition: TypedContractMethod<
    [
      revocationRegistryDefinitionId: BytesLike,
      revocationRegistryDefinition: string
    ],
    [void],
    "nonpayable"
  >;

  registerRevocationStatusList: TypedContractMethod<
    [
      revocationRegistryDefinitionId: BytesLike,
      timestamp: BigNumberish,
      revocationStatusList: string
    ],
    [void],
    "nonpayable"
  >;

  registerSchema: TypedContractMethod<
    [schemaId: BytesLike, schema: string],
    [void],
    "nonpayable"
  >;

  revocationRegistryDefinitions: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  revocationStatusLists: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  revokeAttribute: TypedContractMethod<
    [identity: AddressLike, name: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeDelegate: TypedContractMethod<
    [identity: AddressLike, delegateType: BytesLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  schemas: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  setAttribute: TypedContractMethod<
    [
      identity: AddressLike,
      name: BytesLike,
      value: BytesLike,
      validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDelegate"
  ): TypedContractMethod<
    [
      identity: AddressLike,
      delegateType: BytesLike,
      delegate: AddressLike,
      validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attributes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeOwner"
  ): TypedContractMethod<
    [identity: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentialDefinitions"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "delegates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityOwner"
  ): TypedContractMethod<[identity: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owners"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerCredentialDefinition"
  ): TypedContractMethod<
    [credentialDefinitionId: BytesLike, credentialDefinition: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRevocationRegistryDefinition"
  ): TypedContractMethod<
    [
      revocationRegistryDefinitionId: BytesLike,
      revocationRegistryDefinition: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRevocationStatusList"
  ): TypedContractMethod<
    [
      revocationRegistryDefinitionId: BytesLike,
      timestamp: BigNumberish,
      revocationStatusList: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSchema"
  ): TypedContractMethod<
    [schemaId: BytesLike, schema: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revocationRegistryDefinitions"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "revocationStatusLists"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "revokeAttribute"
  ): TypedContractMethod<
    [identity: AddressLike, name: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDelegate"
  ): TypedContractMethod<
    [identity: AddressLike, delegateType: BytesLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "schemas"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setAttribute"
  ): TypedContractMethod<
    [
      identity: AddressLike,
      name: BytesLike,
      value: BytesLike,
      validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialDefinitionRegistered"
  ): TypedContractEvent<
    CredentialDefinitionRegisteredEvent.InputTuple,
    CredentialDefinitionRegisteredEvent.OutputTuple,
    CredentialDefinitionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DIDAttributeChanged"
  ): TypedContractEvent<
    DIDAttributeChangedEvent.InputTuple,
    DIDAttributeChangedEvent.OutputTuple,
    DIDAttributeChangedEvent.OutputObject
  >;
  getEvent(
    key: "DIDDelegateChanged"
  ): TypedContractEvent<
    DIDDelegateChangedEvent.InputTuple,
    DIDDelegateChangedEvent.OutputTuple,
    DIDDelegateChangedEvent.OutputObject
  >;
  getEvent(
    key: "DIDOwnerChanged"
  ): TypedContractEvent<
    DIDOwnerChangedEvent.InputTuple,
    DIDOwnerChangedEvent.OutputTuple,
    DIDOwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "RevocationRegistryDefinitionRegistered"
  ): TypedContractEvent<
    RevocationRegistryDefinitionRegisteredEvent.InputTuple,
    RevocationRegistryDefinitionRegisteredEvent.OutputTuple,
    RevocationRegistryDefinitionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RevocationStatusListRegistered"
  ): TypedContractEvent<
    RevocationStatusListRegisteredEvent.InputTuple,
    RevocationStatusListRegisteredEvent.OutputTuple,
    RevocationStatusListRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SchemaRegistered"
  ): TypedContractEvent<
    SchemaRegisteredEvent.InputTuple,
    SchemaRegisteredEvent.OutputTuple,
    SchemaRegisteredEvent.OutputObject
  >;

  filters: {
    "CredentialDefinitionRegistered(bytes32,string)": TypedContractEvent<
      CredentialDefinitionRegisteredEvent.InputTuple,
      CredentialDefinitionRegisteredEvent.OutputTuple,
      CredentialDefinitionRegisteredEvent.OutputObject
    >;
    CredentialDefinitionRegistered: TypedContractEvent<
      CredentialDefinitionRegisteredEvent.InputTuple,
      CredentialDefinitionRegisteredEvent.OutputTuple,
      CredentialDefinitionRegisteredEvent.OutputObject
    >;

    "DIDAttributeChanged(address,bytes32,bytes,uint256,uint256)": TypedContractEvent<
      DIDAttributeChangedEvent.InputTuple,
      DIDAttributeChangedEvent.OutputTuple,
      DIDAttributeChangedEvent.OutputObject
    >;
    DIDAttributeChanged: TypedContractEvent<
      DIDAttributeChangedEvent.InputTuple,
      DIDAttributeChangedEvent.OutputTuple,
      DIDAttributeChangedEvent.OutputObject
    >;

    "DIDDelegateChanged(address,bytes32,address,uint256,uint256)": TypedContractEvent<
      DIDDelegateChangedEvent.InputTuple,
      DIDDelegateChangedEvent.OutputTuple,
      DIDDelegateChangedEvent.OutputObject
    >;
    DIDDelegateChanged: TypedContractEvent<
      DIDDelegateChangedEvent.InputTuple,
      DIDDelegateChangedEvent.OutputTuple,
      DIDDelegateChangedEvent.OutputObject
    >;

    "DIDOwnerChanged(address,address,uint256)": TypedContractEvent<
      DIDOwnerChangedEvent.InputTuple,
      DIDOwnerChangedEvent.OutputTuple,
      DIDOwnerChangedEvent.OutputObject
    >;
    DIDOwnerChanged: TypedContractEvent<
      DIDOwnerChangedEvent.InputTuple,
      DIDOwnerChangedEvent.OutputTuple,
      DIDOwnerChangedEvent.OutputObject
    >;

    "RevocationRegistryDefinitionRegistered(bytes32,string)": TypedContractEvent<
      RevocationRegistryDefinitionRegisteredEvent.InputTuple,
      RevocationRegistryDefinitionRegisteredEvent.OutputTuple,
      RevocationRegistryDefinitionRegisteredEvent.OutputObject
    >;
    RevocationRegistryDefinitionRegistered: TypedContractEvent<
      RevocationRegistryDefinitionRegisteredEvent.InputTuple,
      RevocationRegistryDefinitionRegisteredEvent.OutputTuple,
      RevocationRegistryDefinitionRegisteredEvent.OutputObject
    >;

    "RevocationStatusListRegistered(bytes32,uint256,string)": TypedContractEvent<
      RevocationStatusListRegisteredEvent.InputTuple,
      RevocationStatusListRegisteredEvent.OutputTuple,
      RevocationStatusListRegisteredEvent.OutputObject
    >;
    RevocationStatusListRegistered: TypedContractEvent<
      RevocationStatusListRegisteredEvent.InputTuple,
      RevocationStatusListRegisteredEvent.OutputTuple,
      RevocationStatusListRegisteredEvent.OutputObject
    >;

    "SchemaRegistered(bytes32,string)": TypedContractEvent<
      SchemaRegisteredEvent.InputTuple,
      SchemaRegisteredEvent.OutputTuple,
      SchemaRegisteredEvent.OutputObject
    >;
    SchemaRegistered: TypedContractEvent<
      SchemaRegisteredEvent.InputTuple,
      SchemaRegisteredEvent.OutputTuple,
      SchemaRegisteredEvent.OutputObject
    >;
  };
}
