// This file is auto-generated by snarkjs
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

library Pairing {
    struct G1Point {
        uint X;
        uint Y;
    }
    struct G2Point {
        uint[2] X;
        uint[2] Y;
    }
    
    function pairingProd2(G1Point memory a1, G2Point memory a2, G1Point memory b1, G2Point memory b2) internal view returns (bool) {
        uint[12] memory input;
        input[0] = a1.X;
        input[1] = a1.Y;
        input[2] = a2.X[0];
        input[3] = a2.X[1];
        input[4] = a2.Y[0];
        input[5] = a2.Y[1];
        input[6] = b1.X;
        input[7] = b1.Y;
        input[8] = b2.X[0];
        input[9] = b2.X[1];
        input[10] = b2.Y[0];
        input[11] = b2.Y[1];
        uint[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, input, 384, out, 32)
        }
        return success && out[0] != 0;
    }
}

contract AgeVerifier {
    using Pairing for *;
    
    struct VerifyingKey {
        Pairing.G1Point alfa1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }
    
    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }
    
    function verifyingKey() pure internal returns (VerifyingKey memory vk) {
        vk.alfa1 = Pairing.G1Point(uint256(0), uint256(0)); // Will be filled by snarkjs
        vk.beta2 = Pairing.G2Point([uint256(0), uint256(0)], [uint256(0), uint256(0)]);
        vk.gamma2 = Pairing.G2Point([uint256(0), uint256(0)], [uint256(0), uint256(0)]);
        vk.delta2 = Pairing.G2Point([uint256(0), uint256(0)], [uint256(0), uint256(0)]);
        vk.IC = new Pairing.G1Point[](2);
        vk.IC[0] = Pairing.G1Point(uint256(0), uint256(0));
        vk.IC[1] = Pairing.G1Point(uint256(0), uint256(0));
    }
    
    function verifyProof(uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[1] memory input) public view returns (bool) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        
        VerifyingKey memory vk = verifyingKey();
        
        // Compute linear combination vk_x
        Pairing.G1Point memory vk_x = vk.IC[0];
        vk_x = Pairing.G1Point(vk_x.X, vk_x.Y);
        
        // Check pairing equation
        return Pairing.pairingProd2(proof.A, proof.B, vk_x, vk.gamma2);
    }
}