/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ageVerifierGeneratedSol from "./AgeVerifierGenerated.sol";
export type { ageVerifierGeneratedSol };
export type { AgeVerificationRegistry } from "./AgeVerificationRegistry";
export type { AgeVerifier } from "./AgeVerifier";
export type { ZkSyncDidRegistry } from "./ZkSyncDidRegistry";
