/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as artifactsZk from "./artifacts-zk";
export type { artifactsZk };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AgeVerificationRegistry } from "./artifacts-zk/contracts/AgeVerificationRegistry";
export { AgeVerificationRegistry__factory } from "./factories/artifacts-zk/contracts/AgeVerificationRegistry__factory";
export type { AgeVerifier } from "./artifacts-zk/contracts/AgeVerifier";
export { AgeVerifier__factory } from "./factories/artifacts-zk/contracts/AgeVerifier__factory";
export type { Groth16Verifier } from "./artifacts-zk/contracts/AgeVerifierGenerated.sol/Groth16Verifier";
export { Groth16Verifier__factory } from "./factories/artifacts-zk/contracts/AgeVerifierGenerated.sol/Groth16Verifier__factory";
export type { ZkSyncDidRegistry } from "./artifacts-zk/contracts/ZkSyncDidRegistry";
export { ZkSyncDidRegistry__factory } from "./factories/artifacts-zk/contracts/ZkSyncDidRegistry__factory";
export type { ZkSyncDidRegistryAbi } from "./contracts/ZkSyncDidRegistryAbi";
export { ZkSyncDidRegistryAbi__factory } from "./factories/contracts/ZkSyncDidRegistryAbi__factory";
